/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestion_biblioteca.h"
#include <ctype.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>

void gestion_biblioteca_1(char *host)
{
	CLIENT *clnt;
	bool_t *result_1;
	datos_usuario registrarusuario_1_arg;
	bool_t *result_2;
	datos_libro registrarlibro_1_arg;
	int *result_3;
	datos_libro calcularmulta_1_arg;
	int *result_4;
	datos_credencial abrirsesion_1_arg;
	datos_usuario *result_5;
	int consultarusuario_1_arg;
	datos_libro *result_6;
	int buscarlibro_1_arg;
	datos_prestamo *result_7;
	int consultarprestamo_1_arg;
	bool_t *result_8;
	datos_prestamo realizarprestamo_1_arg;
	datos_libro  *result_9;
	int  prestamosusuario_1_arg;
	
#ifndef DEBUG
	clnt = clnt_create(host, gestion_biblioteca, gestion_biblioteca_version, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	int opcion = 0;
	int cont = 0;
	do
	{
		printf("==== Menú Inicio ====\n");
		printf("* 1-Abrir sesión *\n");
		printf("* 2-Salir *\n");
		printf("======================\n");
		printf("Elija la opcion: \n");
		scanf("%d", &opcion);
		while (getchar() != '\n')
			;

		switch (opcion)
		{
		case 1:
			printf("Ingrese el Usuario: \n");
			scanf("%s", abrirsesion_1_arg.usuario);
			printf("Ingrese la contraseña: \n");
			scanf("%s", abrirsesion_1_arg.clave);

			// ACOMODAR QUE LA FUNCINO RETORNE ENTERO PARA QUE EL ADMIN PUEDA INGRESAR VARIAS VECES

			result_4 = abrirsesion_1(&abrirsesion_1_arg, clnt);
			if (result_4 == (int *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}

			if (*result_4 == 1) // acomodar numero o bool?
			{
				do
				{
					printf("==== Menú Admin ====\n");
					printf("* 1-Registrar usuario *\n");
					printf("* 2-Registrar libro *\n");
					printf("* 3-Consultar usuario *\n");
					printf("* 4-Consultar prestamo *\n");
					printf("* 5-Devolucion libro *\n");
					printf("* 6-Salir *\n");
					printf("======================\n");
					printf("Elija la opcion: \n");
					scanf("%d", &opcion);

					while (getchar() != '\n')
						;

					switch (opcion)
					{
					case 1:
						printf("REGISTRAR USUARIOS\n");
						printf("Ingrese los nombres: \n");
						scanf("%s", registrarusuario_1_arg.nombreCompleto);

						printf("Ingrese los apellidos: \n");
						scanf("%s", registrarusuario_1_arg.apellidos);

						printf("Ingrese la ocupación: \n");
						// fgets(registrarusuario_1_arg.ocupacion, 30, stdin);
						scanf("%s", registrarusuario_1_arg.ocupacion);
						// printf("ocupacioooon : %s", registrarusuario_1_arg.ocupacion);
						while (getchar() != '\n');

						printf("Ingrese la identificación: \n");
						scanf("%d", &registrarusuario_1_arg.id);

						printf("Ingrese el usuario: \n");
						scanf("%s", registrarusuario_1_arg.datosCredencial.usuario);

						printf("Ingrese la clave: \n");
						scanf("%s", registrarusuario_1_arg.datosCredencial.clave);


						while (getchar() != '\n');

						result_1 = registrarusuario_1(&registrarusuario_1_arg, clnt);
						if (result_1 == (bool_t *)NULL)
						{
							clnt_perror(clnt, "call failed\n");
						}

						else if (*result_1 == TRUE)
						{
							printf("Usuario registrado Exitosamente \n");
						}
						else
						{
							printf("Usuario NO registrado\n");
						}
						break;

					// opcion para registrar los libros
					case 2:
						printf("REGISTRAR LIBROS\n");
						printf("Ingrese el nombre del libro: \n");
						fgets(registrarlibro_1_arg.nombre, 30, stdin);

						printf("Ingrese el autor: \n");
						fgets(registrarlibro_1_arg.autor, 30, stdin);

						printf("Ingrese el area de conocimiento: \n");
						fgets(registrarlibro_1_arg.areaConocimiento, 30, stdin);

						printf("Ingrese la editorial \n");
						fgets(registrarlibro_1_arg.editorial, 30, stdin);

						printf("Ingrese el código: \n");
						scanf("%d", &registrarlibro_1_arg.codigo);

						while (getchar() != '\n')
							;
						result_2 = registrarlibro_1(&registrarlibro_1_arg, clnt);
						if (result_2 == (bool_t *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_1 == TRUE)
						{
							printf("Libro registrado Exitosamente \n");
						}
						else
						{
							printf("Libro NO registrado\n");
						}
						break;

					// Opcion para consultar usuarios
					case 3:
						printf("CONSULTAR USUARIOS\n");
						printf("Digite la identificación del usuario: \n");
						scanf("%d", &consultarusuario_1_arg);
						result_5 = consultarusuario_1(&consultarusuario_1_arg, clnt);
						if (result_5 == (datos_usuario *)NULL)
						{
							clnt_perror(clnt, "call failed\n");
						}

						if ((*result_5).id == consultarusuario_1_arg)
						{
							printf("Nombre: %s \n", (*result_5).nombreCompleto);
							printf("Apellidos: %s \n", (*result_5).apellidos);
							printf("Identificación: %d \n", (*result_5).id);
							printf("Usuario: %s\n", (*result_5).datosCredencial.usuario);
							printf("Ocupación: %s \n", (*result_5).ocupacion);
							printf("\n");
						}
						else
						{
							printf("Usuario NO encontrado \n");
						}
						break;
					//Opcion para consultar un prestamo
					case 4:
						printf("CONSULTAR PRESTAMO\n");
						printf("Digite el codigo del prestamo: \n");
						scanf("%d", &consultarprestamo_1_arg);
						result_7 = consultarprestamo_1(&consultarprestamo_1_arg, clnt);
						if (result_7 == (datos_prestamo *)NULL)
						{
							clnt_perror(clnt, "call failed\n");
						}

						if ((*result_7).codigo == consultarprestamo_1_arg)
						{
							printf("Codigo del prestamo: %d \n", (*result_7).codigo);
							printf("Nombre usuario: %s \n", (*result_7).usuarioAsociado.nombreCompleto);
							printf("Identificacion usuario: %d \n", (*result_7).usuarioAsociado.id);
							printf("Nombre del libro: %s", (*result_7).libroaPrestar.nombre);
							printf("Codigo del libro: %d\n", (*result_7).libroaPrestar.codigo);
							printf("Fecha de prestamo: %s \n", (*result_7).fechaPrestamo);
							printf("Fecha de devolucion: %s \n", (*result_7).fechaDevolucion);
							printf("\n");
						}
						else
						{
							printf("Prestamo NO encontrado \n");
						}
						break;
					case 5:
						printf("DEVOLUCION LIBRO\n");
						int codPrestamo = 0;
						datos_prestamo *objP;
						printf("Digite el codigo del prestamo: \n");
						scanf("%d", &codPrestamo);
						objP = consultarprestamo_1(&codPrestamo, clnt);
						if (objP == (datos_prestamo *)NULL)
						{
							clnt_perror(clnt, "call failed consulta prestamo\n");
						}						

						if ((*objP).codigo == codPrestamo)
						{
							calcularmulta_1_arg = objP->libroaPrestar;
														
							result_3 = calcularmulta_1(&calcularmulta_1_arg, clnt);
							//printf("RESULTADO %d\n", (*result_3));
							if (result_3 == (int *) NULL) {
								clnt_perror (clnt, "call failed devolucion prestamo");
							}
							if(*result_3 != 0){
								printf("RECIBO DE PAGO");
								printf("Nombre del usuario: %s %s\n",(*objP).usuarioAsociado.nombreCompleto, (*objP).usuarioAsociado.apellidos);
								printf("Nombre del libro: %s", (*objP).libroaPrestar.nombre);
								printf("El valor de la multa es: %d\n", *result_3);
							}else{
								printf("El usuario no tiene multas, puede hacerse la devolución del libro\n");
							}
							
						}else{
							printf("El libro no se encuentra registrado");
						}

						break;
					// opcion para salir de la aplicacion
					case 6:
						printf("Exit....\n");
						break;
					}
				} while (opcion != 6);
			}
			else if (*result_4 == 2) // NUMERO O BOOL?
			{
				do
				{
					printf("==== Menú Usuario ====\n");
					printf("* 1-Consultar libros *\n");
					printf("* 2-Solicitar el préstamo de un libro *\n");
					printf("* 3-Salir *\n");
					printf("======================\n");
					printf("Elija la opcion: \n");
					scanf("%d", &opcion);

					while (getchar() != '\n');

					switch (opcion)
					{
					case 1:
						// Opcion para consultar libros

						printf("CONSULTAR LIBROS\n");
						printf("Digite el código del libro a buscar: \n");
						scanf("%d", &buscarlibro_1_arg);

						result_6 = buscarlibro_1(&buscarlibro_1_arg, clnt);
						if (result_6 == (datos_libro *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}

						// ACOMODAR LA FUNCION PORQUE DEBE DEVOLVER VARIOS LIBROS
						if ((*result_6).codigo == buscarlibro_1_arg)
						{
							printf("Información del personal: \n");
							printf("Nombre del libro: %s ", (*result_6).nombre);
							printf("Autor: %s \n", (*result_6).autor);
							printf("Area de conocimiento: %s \n", (*result_6).areaConocimiento);
							printf("Editorial: %s\n", (*result_6).editorial);
							printf("Código: %d\n", (*result_6).codigo);
							printf("\n");
						}
						else
						{
							printf("Libros no encontrados a partir del tipo de busqueda realizada \n");
						}
						break;

					case 2:
						printf("SOLICITAR PRESTAMO \n");
						//int idUsuario = 0;
						int idLibro = 0;
						datos_usuario *objUsu;
						datos_libro *objLib;
						datos_libro objLibPrestado;
						printf("Digite la identificación del usuario: \n");
						scanf("%d", &prestamosusuario_1_arg);
						
						objUsu = consultarusuario_1(&prestamosusuario_1_arg, clnt);
						if (objUsu == (datos_usuario *)NULL)
						{
							clnt_perror(clnt, "call failed\n");
						}
						if ((*objUsu).id == prestamosusuario_1_arg)
						{
							int opcion = 0;
														
							printf("Es la primera vez que solicita un prestamo? (1 = si/2 = no)\n");
							scanf("%d", &opcion);

							if(opcion == 1){
								printf("Digite el id del libro: \n");
								scanf("%d", &idLibro);
									
								objLib = buscarlibro_1(&idLibro, clnt);
								if (objLib == (datos_libro *)NULL)
								{
									clnt_perror(clnt, "call failed\n");
								}
								if ((*objLib).codigo == idLibro)
								{
									realizarprestamo_1_arg.libroaPrestar = (*objLib);
									realizarprestamo_1_arg.usuarioAsociado = (*objUsu);
									printf("Ingrese el código del prestamo: \n");
									scanf("%d", &realizarprestamo_1_arg.codigo);
									printf("Ingrese la fecha del prestamo: \n");
									scanf("%s", realizarprestamo_1_arg.fechaPrestamo);
									printf("Ingrese la fecha de devolucion del libro: \n");
									scanf("%s", realizarprestamo_1_arg.fechaDevolucion);
									realizarprestamo_1_arg.multa = false;
									realizarprestamo_1_arg.valor_multa = 0;
									printf("\n");
									result_8 = realizarprestamo_1(&realizarprestamo_1_arg, clnt);
									if (result_8 == (bool_t *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									else if (*result_1 == TRUE)
									{
										printf("Prestamo registrado Exitosamente \n");
									}
									else
									{
										printf("Prestamo NO registrado\n");
									}
								}else
								{
									printf("Libro NO encontrado \n");
								}
							}else if(opcion == 2){
								result_9 = prestamosusuario_1(&prestamosusuario_1_arg, clnt);
							
								if (result_9 == (datos_libro *)NULL) {
									clnt_perror (clnt, "call failed");
								
								}
								objLibPrestado = *result_9;
								int *valor_multa;							
								valor_multa = calcularmulta_1(&objLibPrestado, clnt);
								if (valor_multa == (int *) NULL) {
									clnt_perror(clnt, "call failed\n");
								}
								if(*valor_multa < 20000){
									printf("Digite el id del libro: \n");
									scanf("%d", &idLibro);
									
									objLib = buscarlibro_1(&idLibro, clnt);
									if (objLib == (datos_libro *)NULL)
									{
										clnt_perror(clnt, "call failed\n");
									}
									if ((*objLib).codigo == idLibro)
									{
										realizarprestamo_1_arg.libroaPrestar = (*objLib);
										realizarprestamo_1_arg.usuarioAsociado = (*objUsu);
										printf("Ingrese el código del prestamo: \n");
										scanf("%d", &realizarprestamo_1_arg.codigo);
										printf("Ingrese la fecha del prestamo: \n");
										scanf("%s", realizarprestamo_1_arg.fechaPrestamo);
										printf("Ingrese la fecha de devolucion del libro: \n");
										scanf("%s", realizarprestamo_1_arg.fechaDevolucion);
										realizarprestamo_1_arg.multa = false;
										realizarprestamo_1_arg.valor_multa = 0;
										printf("\n");
										result_8 = realizarprestamo_1(&realizarprestamo_1_arg, clnt);
										if (result_8 == (bool_t *) NULL) {
											clnt_perror (clnt, "call failed");
										}
										else if (*result_1 == TRUE)
										{
											printf("Prestamo registrado Exitosamente \n");
										}
										else
										{
											printf("Prestamo NO registrado\n");
										}
									}else
									{
										printf("Libro NO encontrado \n");
									}
								}else{
									printf("El usuario no puede solicitar prestamo ya que tiene una multa mayor a 20000 pesos");
								}
							}else{
								printf("Opción no válida");
							}						
						}
						else
						{
							printf("Usuario NO encontrado \n");
						}
						break;

					case 3:
						printf("Exit....\n");
						break;
					}
				} while (opcion != 3);
			}
			else
			{
				printf("No se ingresaron correctamente los datos. Verificar la información\n");
			}
			break;

		case 2:
			printf("Exit....\n");
			break;
		}
	} while (opcion != 2);




	
	
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	gestion_biblioteca_1(host);
	exit(0);
}
