/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestion_notificaciones.h"

bool_t *
enviarnotificacion_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("Mensaje recibido: %s \n", *argp);

	return &result;
}
