/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTION_BIBLIOTECA_H_RPCGEN
#define _GESTION_BIBLIOTECA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXDAT 20

struct datos_credencial {
	char usuario[MAXNOM];
	char clave[MAXDAT];
};
typedef struct datos_credencial datos_credencial;

struct datos_usuario {
	int id;
	char nombreCompleto[MAXNOM];
	char apellidos[MAXNOM];
	char ocupacion[MAXNOM];
	struct datos_credencial datosCredencial;
};
typedef struct datos_usuario datos_usuario;

struct datos_libro {
	int codigo;
	char nombre[MAXNOM];
	char areaConocimiento[MAXNOM];
	char autor[MAXNOM];
	char editorial[MAXNOM];
};
typedef struct datos_libro datos_libro;

struct datos_prestamo {
	int codigo;
	char fechaPrestamo[MAXDAT];
	char fechaDevolucion[MAXDAT];
	bool_t multa;
	int valor_multa;
	struct datos_libro libroaPrestar;
	struct datos_usuario usuarioAsociado;
};
typedef struct datos_prestamo datos_prestamo;

#define gestion_biblioteca 0x20000021
#define gestion_biblioteca_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarUsuario 1
extern  bool_t * registrarusuario_1(datos_usuario *, CLIENT *);
extern  bool_t * registrarusuario_1_svc(datos_usuario *, struct svc_req *);
#define registrarLibro 2
extern  bool_t * registrarlibro_1(datos_libro *, CLIENT *);
extern  bool_t * registrarlibro_1_svc(datos_libro *, struct svc_req *);
#define calcularMulta 3
extern  int * calcularmulta_1(datos_libro *, CLIENT *);
extern  int * calcularmulta_1_svc(datos_libro *, struct svc_req *);
#define abrirSesion 4
extern  int * abrirsesion_1(datos_credencial *, CLIENT *);
extern  int * abrirsesion_1_svc(datos_credencial *, struct svc_req *);
#define consultarUsuario 5
extern  datos_usuario * consultarusuario_1(int *, CLIENT *);
extern  datos_usuario * consultarusuario_1_svc(int *, struct svc_req *);
#define buscarLibro 6
extern  datos_libro * buscarlibro_1(int *, CLIENT *);
extern  datos_libro * buscarlibro_1_svc(int *, struct svc_req *);
#define consultarPrestamo 7
extern  datos_prestamo * consultarprestamo_1(int *, CLIENT *);
extern  datos_prestamo * consultarprestamo_1_svc(int *, struct svc_req *);
#define realizarPrestamo 8
extern  bool_t * realizarprestamo_1(datos_prestamo *, CLIENT *);
extern  bool_t * realizarprestamo_1_svc(datos_prestamo *, struct svc_req *);
#define prestamosUsuario 9
extern  datos_libro * prestamosusuario_1(int *, CLIENT *);
extern  datos_libro * prestamosusuario_1_svc(int *, struct svc_req *);
extern int gestion_biblioteca_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarUsuario 1
extern  bool_t * registrarusuario_1();
extern  bool_t * registrarusuario_1_svc();
#define registrarLibro 2
extern  bool_t * registrarlibro_1();
extern  bool_t * registrarlibro_1_svc();
#define calcularMulta 3
extern  int * calcularmulta_1();
extern  int * calcularmulta_1_svc();
#define abrirSesion 4
extern  int * abrirsesion_1();
extern  int * abrirsesion_1_svc();
#define consultarUsuario 5
extern  datos_usuario * consultarusuario_1();
extern  datos_usuario * consultarusuario_1_svc();
#define buscarLibro 6
extern  datos_libro * buscarlibro_1();
extern  datos_libro * buscarlibro_1_svc();
#define consultarPrestamo 7
extern  datos_prestamo * consultarprestamo_1();
extern  datos_prestamo * consultarprestamo_1_svc();
#define realizarPrestamo 8
extern  bool_t * realizarprestamo_1();
extern  bool_t * realizarprestamo_1_svc();
#define prestamosUsuario 9
extern  datos_libro * prestamosusuario_1();
extern  datos_libro * prestamosusuario_1_svc();
extern int gestion_biblioteca_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_credencial (XDR *, datos_credencial*);
extern  bool_t xdr_datos_usuario (XDR *, datos_usuario*);
extern  bool_t xdr_datos_libro (XDR *, datos_libro*);
extern  bool_t xdr_datos_prestamo (XDR *, datos_prestamo*);

#else /* K&R C */
extern bool_t xdr_datos_credencial ();
extern bool_t xdr_datos_usuario ();
extern bool_t xdr_datos_libro ();
extern bool_t xdr_datos_prestamo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTION_BIBLIOTECA_H_RPCGEN */
