/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "gestion_biblioteca.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
registrarusuario_1(datos_usuario *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrarUsuario,
		(xdrproc_t) xdr_datos_usuario, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
registrarlibro_1(datos_libro *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrarLibro,
		(xdrproc_t) xdr_datos_libro, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
calcularmulta_1(datos_libro *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calcularMulta,
		(xdrproc_t) xdr_datos_libro, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
abrirsesion_1(datos_credencial *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, abrirSesion,
		(xdrproc_t) xdr_datos_credencial, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_usuario *
consultarusuario_1(int *argp, CLIENT *clnt)
{
	static datos_usuario clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarUsuario,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_usuario, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_libro *
buscarlibro_1(int *argp, CLIENT *clnt)
{
	static datos_libro clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, buscarLibro,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_libro, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_prestamo *
consultarprestamo_1(int *argp, CLIENT *clnt)
{
	static datos_prestamo clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarPrestamo,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_prestamo, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
realizarprestamo_1(datos_prestamo *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, realizarPrestamo,
		(xdrproc_t) xdr_datos_prestamo, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_libro *
prestamosusuario_1(int *argp, CLIENT *clnt)
{
	static datos_libro clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, prestamosUsuario,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_libro, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
